### PR TITLE
Login/register microservices with database

### PR DESCRIPTION
**Pull request by AndyHCode**
Linked login and register microservices with the database API. It will return a string "success" or "fail" for now.

### CODE REVIEW

**Review by AliChowdhuryA — APPROVED** [review]
Why is apigateway on port 5050? Will discuss then approve

discussion: port 5050 is a large number so we wouldnt expect anyone to use it

**Review by R3aLyze — APPROVED** [review]
Looks good! Just make a new commit to the branch and update the port to 5000

**Comment by AndyHCode** [comment]
What do you mean change it to port 5000? I thought that api gateway is using port 5000

**Comment by R3aLyze** [comment]
No, the port for the database.py is set to 5050

**Comment by AndyHCode** [comment]
I can change the port to 5011 since I seem like no one is using it and it seem there a range of port you guys exposed in the docker file

**Comment by AliChowdhuryA** [comment]
nobody is using port 5000 either

**Comment by R3aLyze** [comment]
5011 is fine

**Pull request merged**
